repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        description: flake8 enforcement
        entry: flake8
        args: ["--config=setup.cfg"]
        language: python
        types: [python]
